function txt = getCurrentStatus(status_ID)
    status_man = cell(1,4);
    status_man(1) = {{'ACTIONS:','1) Move slider to browse EMG epochs.',...
                                 '2) Press DONE to accept current results.',...
                                 '3) Select the radio button below each epoch to',...
                                 '    perform manual selection of active period.',...
                                 '4) Adjust auto-detection parameters and press',...
                                 '    RECOMPUTE'}};
    status_man(2) = {{'STATUS:',' Chosing active EMG manually...'}};
    status_man(3) = {{'STATUS:',' Recomputing active periods, please wait...'}};
    txt = status_man{status_ID};
end